/**
 * Item definitions for the Knight Online calculator
 * lib/calculator/items.ts
 */

import { ItemStat } from './types'

// ─── Types ────────────────────────────────────────────────────────────────────

export type ItemGradeType = 'Normal' | 'Reverse' | 'Rare' | 'Unique' | 'Draki' | 'Accessories'

export interface ItemGrade {
  id: number
  label: string
}

export interface ItemEntry {
  id: string
  name: string
  categoryId: string
  isReversible: boolean
  isRare: boolean
  isUnique: boolean
  isDraki: boolean
  canEquipRight: boolean
  canEquipLeft: boolean
  canEquipNormal: boolean
  setIdentifiers?: string[]
  baseStats: ItemStat
}

export interface ItemCategory {
  id: string
  name: string
}

// ─── Categories ───────────────────────────────────────────────────────────────

export const ITEM_CATEGORIES: ItemCategory[] = [
  { id: 'weapon-warrior', name: 'Silah - Warrior' },
  { id: 'weapon-rogue',   name: 'Silah - Rogue' },
  { id: 'weapon-priest',  name: 'Silah - Priest' },
  { id: 'weapon-mage',    name: 'Silah - Mage' },
  { id: 'weapon-kurian',  name: 'Silah - Kurian' },
  { id: 'armor-warrior',  name: 'Zırh - Warrior' },
  { id: 'armor-rogue',    name: 'Zırh - Rogue' },
  { id: 'armor-priest',   name: 'Zırh - Priest' },
  { id: 'armor-mage',     name: 'Zırh - Mage' },
  { id: 'armor-kurian',   name: 'Zırh - Kurian' },
  { id: 'accessories',    name: 'Accessories' },
  { id: 'pathos',         name: 'Pathos' },
  { id: 'tattoo',         name: 'Tattoo / Wings / Emblem' },
]

// ─── Grade Helpers ────────────────────────────────────────────────────────────

export const NORMAL_GRADES: ItemGrade[] = [
  { id: 0, label: 'Normal' },
  { id: 1, label: '+1' },
  { id: 2, label: '+2' },
  { id: 3, label: '+3' },
  { id: 4, label: '+4' },
  { id: 5, label: '+5' },
  { id: 6, label: '+6' },
  { id: 7, label: '+7' },
  { id: 8, label: '+8' },
  { id: 9, label: '+9' },
]

// ─── Item List ────────────────────────────────────────────────────────────────

export const ITEM_LIST: ItemEntry[] = [
  // ── Weapon - Warrior ──────────────────────────────────────────────────────
  {
    id: 'krowaz-chieftain-sword',
    name: 'Krowaz Chieftain Sword',
    categoryId: 'weapon-warrior',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 90,
      attackSpeed: 65,
      weight: 80,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 200,
    },
  },
  {
    id: 'krowaz-chieftain-axe',
    name: 'Krowaz Chieftain Axe',
    categoryId: 'weapon-warrior',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 92,
      attackSpeed: 60,
      weight: 90,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 210,
    },
  },
  {
    id: 'krowaz-chieftain-dual-sword',
    name: 'Krowaz Chieftain Dual Sword',
    categoryId: 'weapon-warrior',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: true,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 88,
      attackSpeed: 70,
      weight: 70,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 190,
    },
  },
  {
    id: 'iron-bow-warrior',
    name: 'Iron Bow',
    categoryId: 'weapon-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    baseStats: {
      attackPower: 75,
      attackSpeed: 55,
      effectiveRange: 15,
      weight: 60,
      durability: 150,
      requiredLevel: 75,
      requiredStr: 150,
    },
  },
  {
    id: 'krowaz-chieftain-great-sword',
    name: 'Krowaz Chieftain Great Sword',
    categoryId: 'weapon-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 95,
      attackSpeed: 55,
      weight: 110,
      durability: 220,
      requiredLevel: 83,
      requiredStr: 230,
    },
  },

  // ── Weapon - Rogue ────────────────────────────────────────────────────────
  {
    id: 'krowaz-assassin-dagger-r',
    name: 'Krowaz Assassin Dagger (Right)',
    categoryId: 'weapon-rogue',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 85,
      attackSpeed: 75,
      weight: 50,
      durability: 180,
      requiredLevel: 83,
      requiredDex: 200,
    },
  },
  {
    id: 'krowaz-assassin-dagger-l',
    name: 'Krowaz Assassin Dagger (Left)',
    categoryId: 'weapon-rogue',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: true,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 85,
      attackSpeed: 75,
      weight: 50,
      durability: 180,
      requiredLevel: 83,
      requiredDex: 200,
    },
  },
  {
    id: 'krowaz-archer-bow',
    name: 'Krowaz Archer Bow',
    categoryId: 'weapon-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 88,
      attackSpeed: 65,
      effectiveRange: 18,
      weight: 55,
      durability: 180,
      requiredLevel: 83,
      requiredDex: 210,
    },
  },
  {
    id: 'krowaz-assassin-sword',
    name: 'Krowaz Assassin Sword',
    categoryId: 'weapon-rogue',
    isReversible: true,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: true,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 83,
      attackSpeed: 78,
      weight: 48,
      durability: 180,
      requiredLevel: 83,
      requiredDex: 195,
    },
  },

  // ── Weapon - Priest ───────────────────────────────────────────────────────
  {
    id: 'krowaz-priest-club',
    name: 'Krowaz Priest Club',
    categoryId: 'weapon-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 80,
      attackSpeed: 68,
      weight: 65,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 170,
    },
  },
  {
    id: 'krowaz-priest-sword',
    name: 'Krowaz Priest Sword',
    categoryId: 'weapon-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 82,
      attackSpeed: 70,
      weight: 60,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 175,
    },
  },
  {
    id: 'krowaz-priest-club-2h',
    name: 'Krowaz Priest Club (2H)',
    categoryId: 'weapon-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 86,
      attackSpeed: 58,
      weight: 90,
      durability: 220,
      requiredLevel: 83,
      requiredStr: 190,
    },
  },
  {
    id: 'krowaz-priest-mace',
    name: 'Krowaz Priest Mace',
    categoryId: 'weapon-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 78,
      attackSpeed: 72,
      weight: 55,
      durability: 190,
      requiredLevel: 83,
      requiredStr: 165,
    },
  },

  // ── Weapon - Mage ─────────────────────────────────────────────────────────
  {
    id: 'krowaz-mage-staff',
    name: 'Krowaz Mage Staff',
    categoryId: 'weapon-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 85,
      attackSpeed: 62,
      weight: 70,
      durability: 190,
      requiredLevel: 83,
      requiredInt: 200,
    },
  },
  {
    id: 'krowaz-mage-wand',
    name: 'Krowaz Mage Wand',
    categoryId: 'weapon-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 82,
      attackSpeed: 68,
      weight: 50,
      durability: 190,
      requiredLevel: 83,
      requiredInt: 195,
    },
  },
  {
    id: 'krowaz-mage-scepter',
    name: 'Krowaz Mage Scepter',
    categoryId: 'weapon-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 88,
      attackSpeed: 60,
      weight: 75,
      durability: 200,
      requiredLevel: 83,
      requiredInt: 210,
    },
  },
  {
    id: 'krowaz-mage-staff-2h',
    name: 'Krowaz Mage Staff (2H)',
    categoryId: 'weapon-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz'],
    baseStats: {
      attackPower: 92,
      attackSpeed: 55,
      weight: 100,
      durability: 210,
      requiredLevel: 83,
      requiredInt: 220,
    },
  },

  // ── Weapon - Kurian ───────────────────────────────────────────────────────
  {
    id: 'krowaz-kurian-sword',
    name: 'Krowaz Kurian Sword',
    categoryId: 'weapon-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      attackPower: 90,
      attackSpeed: 65,
      weight: 80,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 200,
    },
  },
  {
    id: 'krowaz-kurian-axe',
    name: 'Krowaz Kurian Axe',
    categoryId: 'weapon-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      attackPower: 93,
      attackSpeed: 58,
      weight: 95,
      durability: 210,
      requiredLevel: 83,
      requiredStr: 215,
    },
  },
  {
    id: 'krowaz-kurian-club',
    name: 'Krowaz Kurian Club',
    categoryId: 'weapon-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      attackPower: 87,
      attackSpeed: 70,
      weight: 70,
      durability: 200,
      requiredLevel: 83,
      requiredStr: 185,
    },
  },
  {
    id: 'krowaz-kurian-spear',
    name: 'Krowaz Kurian Spear',
    categoryId: 'weapon-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: true,
    canEquipLeft: false,
    canEquipNormal: false,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      attackPower: 88,
      attackSpeed: 62,
      weight: 85,
      durability: 205,
      requiredLevel: 83,
      requiredStr: 195,
    },
  },

  // ── Armor - Warrior ───────────────────────────────────────────────────────
  {
    id: 'krowaz-warrior-helm',
    name: 'Krowaz Warrior Helm',
    categoryId: 'armor-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 80,
      bonusStrength: 5,
      durability: 300,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-warrior-pads',
    name: 'Krowaz Warrior Pads',
    categoryId: 'armor-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 120,
      bonusStrength: 7,
      durability: 350,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-warrior-pauldron',
    name: 'Krowaz Warrior Pauldron',
    categoryId: 'armor-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 90,
      bonusStrength: 5,
      durability: 300,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-warrior-boots',
    name: 'Krowaz Warrior Boots',
    categoryId: 'armor-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 70,
      bonusStrength: 4,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-warrior-gauntlets',
    name: 'Krowaz Warrior Gauntlets',
    categoryId: 'armor-warrior',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 65,
      bonusStrength: 4,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },

  // ── Armor - Rogue ─────────────────────────────────────────────────────────
  {
    id: 'krowaz-rogue-helm',
    name: 'Krowaz Rogue Helm',
    categoryId: 'armor-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 80,
      bonusDexterity: 5,
      durability: 280,
      requiredLevel: 83,
      requiredDex: 175,
    },
  },
  {
    id: 'krowaz-rogue-pads',
    name: 'Krowaz Rogue Pads',
    categoryId: 'armor-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 120,
      bonusDexterity: 7,
      durability: 320,
      requiredLevel: 83,
      requiredDex: 175,
    },
  },
  {
    id: 'krowaz-rogue-pauldron',
    name: 'Krowaz Rogue Pauldron',
    categoryId: 'armor-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 90,
      bonusDexterity: 5,
      durability: 280,
      requiredLevel: 83,
      requiredDex: 175,
    },
  },
  {
    id: 'krowaz-rogue-boots',
    name: 'Krowaz Rogue Boots',
    categoryId: 'armor-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 70,
      bonusDexterity: 4,
      durability: 240,
      requiredLevel: 83,
      requiredDex: 175,
    },
  },
  {
    id: 'krowaz-rogue-gauntlets',
    name: 'Krowaz Rogue Gauntlets',
    categoryId: 'armor-rogue',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 65,
      bonusDexterity: 4,
      durability: 240,
      requiredLevel: 83,
      requiredDex: 175,
    },
  },

  // ── Armor - Priest ────────────────────────────────────────────────────────
  {
    id: 'krowaz-priest-helm',
    name: 'Krowaz Priest Helm',
    categoryId: 'armor-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 80,
      bonusStrength: 4,
      bonusIntelligence: 2,
      durability: 290,
      requiredLevel: 83,
      requiredStr: 160,
    },
  },
  {
    id: 'krowaz-priest-pads',
    name: 'Krowaz Priest Pads',
    categoryId: 'armor-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 120,
      bonusStrength: 5,
      bonusIntelligence: 3,
      durability: 330,
      requiredLevel: 83,
      requiredStr: 160,
    },
  },
  {
    id: 'krowaz-priest-pauldron',
    name: 'Krowaz Priest Pauldron',
    categoryId: 'armor-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 90,
      bonusStrength: 4,
      bonusIntelligence: 2,
      durability: 290,
      requiredLevel: 83,
      requiredStr: 160,
    },
  },
  {
    id: 'krowaz-priest-boots',
    name: 'Krowaz Priest Boots',
    categoryId: 'armor-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 70,
      bonusStrength: 3,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 160,
    },
  },
  {
    id: 'krowaz-priest-gauntlets',
    name: 'Krowaz Priest Gauntlets',
    categoryId: 'armor-priest',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 65,
      bonusStrength: 3,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 160,
    },
  },

  // ── Armor - Mage ──────────────────────────────────────────────────────────
  {
    id: 'krowaz-mage-helm',
    name: 'Krowaz Mage Helm',
    categoryId: 'armor-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 80,
      bonusIntelligence: 5,
      durability: 270,
      requiredLevel: 83,
      requiredInt: 180,
    },
  },
  {
    id: 'krowaz-mage-pads',
    name: 'Krowaz Mage Pads',
    categoryId: 'armor-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 120,
      bonusIntelligence: 7,
      durability: 310,
      requiredLevel: 83,
      requiredInt: 180,
    },
  },
  {
    id: 'krowaz-mage-pauldron',
    name: 'Krowaz Mage Pauldron',
    categoryId: 'armor-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 90,
      bonusIntelligence: 5,
      durability: 270,
      requiredLevel: 83,
      requiredInt: 180,
    },
  },
  {
    id: 'krowaz-mage-boots',
    name: 'Krowaz Mage Boots',
    categoryId: 'armor-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 70,
      bonusIntelligence: 4,
      durability: 230,
      requiredLevel: 83,
      requiredInt: 180,
    },
  },
  {
    id: 'krowaz-mage-gauntlets',
    name: 'Krowaz Mage Gauntlets',
    categoryId: 'armor-mage',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      defense: 65,
      bonusIntelligence: 4,
      durability: 230,
      requiredLevel: 83,
      requiredInt: 180,
    },
  },

  // ── Armor - Kurian ────────────────────────────────────────────────────────
  {
    id: 'krowaz-kurian-helm',
    name: 'Krowaz Kurian Helm',
    categoryId: 'armor-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      defense: 80,
      bonusStrength: 5,
      durability: 300,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-kurian-pads',
    name: 'Krowaz Kurian Pads',
    categoryId: 'armor-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      defense: 120,
      bonusStrength: 7,
      durability: 350,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-kurian-pauldron',
    name: 'Krowaz Kurian Pauldron',
    categoryId: 'armor-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      defense: 90,
      bonusStrength: 5,
      durability: 300,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-kurian-boots',
    name: 'Krowaz Kurian Boots',
    categoryId: 'armor-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      defense: 70,
      bonusStrength: 4,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },
  {
    id: 'krowaz-kurian-gauntlets',
    name: 'Krowaz Kurian Gauntlets',
    categoryId: 'armor-kurian',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz-kurian'],
    baseStats: {
      defense: 65,
      bonusStrength: 4,
      durability: 250,
      requiredLevel: 83,
      requiredStr: 180,
    },
  },

  // ── Accessories ───────────────────────────────────────────────────────────
  {
    id: 'krowaz-ring',
    name: 'Krowaz Ring',
    categoryId: 'accessories',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      bonusStrength: 5,
      requiredLevel: 83,
    },
  },
  {
    id: 'krowaz-earring',
    name: 'Krowaz Earring',
    categoryId: 'accessories',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      bonusDexterity: 5,
      requiredLevel: 83,
    },
  },
  {
    id: 'krowaz-necklace',
    name: 'Krowaz Necklace',
    categoryId: 'accessories',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      bonusIntelligence: 5,
      requiredLevel: 83,
    },
  },
  {
    id: 'iron-ring',
    name: 'Iron Ring',
    categoryId: 'accessories',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      bonusStrength: 3,
      requiredLevel: 60,
    },
  },

  // ── Pathos ────────────────────────────────────────────────────────────────
  {
    id: 'iron-pathos',
    name: 'Iron Pathos',
    categoryId: 'pathos',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      damagePercentage: 3,
      requiredLevel: 70,
    },
  },
  {
    id: 'steel-pathos',
    name: 'Steel Pathos',
    categoryId: 'pathos',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      damagePercentage: 5,
      requiredLevel: 75,
    },
  },
  {
    id: 'krowaz-pathos',
    name: 'Krowaz Pathos',
    categoryId: 'pathos',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      damagePercentage: 7,
      requiredLevel: 83,
    },
  },
  {
    id: 'bronze-pathos',
    name: 'Bronze Pathos',
    categoryId: 'pathos',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      damagePercentage: 2,
      requiredLevel: 65,
    },
  },

  // ── Tattoo / Wings / Emblem ───────────────────────────────────────────────
  {
    id: 'krowaz-tattoo',
    name: 'Krowaz Tattoo',
    categoryId: 'tattoo',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      bonusStrength: 3,
      bonusDexterity: 3,
      requiredLevel: 83,
    },
  },
  {
    id: 'iron-wings',
    name: 'Iron Wings',
    categoryId: 'tattoo',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      defense: 20,
      requiredLevel: 70,
    },
  },
  {
    id: 'silver-emblem',
    name: 'Silver Emblem',
    categoryId: 'tattoo',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    baseStats: {
      bonusStrength: 2,
      bonusDexterity: 2,
      requiredLevel: 75,
    },
  },
  {
    id: 'krowaz-emblem',
    name: 'Krowaz Emblem',
    categoryId: 'tattoo',
    isReversible: false,
    isRare: false,
    isUnique: false,
    isDraki: false,
    canEquipRight: false,
    canEquipLeft: false,
    canEquipNormal: true,
    setIdentifiers: ['krowaz'],
    baseStats: {
      bonusStrength: 4,
      bonusDexterity: 4,
      requiredLevel: 83,
    },
  },
]

// ─── Helper Functions ─────────────────────────────────────────────────────────

/**
 * Returns all item categories
 */
export function getItemCategories(): ItemCategory[] {
  return ITEM_CATEGORIES
}

/**
 * Returns all items belonging to the given category
 */
export function getItemsByCategory(categoryId: string): ItemEntry[] {
  return ITEM_LIST.filter((item) => item.categoryId === categoryId)
}

/**
 * Returns the item with the given id, or undefined if not found
 */
export function getItemById(itemId: string): ItemEntry | undefined {
  return ITEM_LIST.find((item) => item.id === itemId)
}

/**
 * Returns the applicable upgrade grades for a given item.
 * Accessories and non-reversible unique/rare items only have grade 0 (Normal).
 * All other items support +0 through +9.
 */
export function getItemGrades(item: ItemEntry): ItemGrade[] {
  if (item.categoryId === 'accessories') {
    return [{ id: 0, label: 'Normal' }]
  }
  return NORMAL_GRADES
}
